version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      APP_DATABASE_DSN: "host=host.docker.internal user=postgres password=postgres dbname=app port=5432 sslmode=disable"
      APP_DATABASE__DSN: "host=host.docker.internal user=postgres password=postgres dbname=app port=5432 sslmode=disable"
      APP_REDIS_ADDR: "redis:6379"
      APP_REDIS__ADDR: "redis:6379"
      APP_JWT_SECRET: change_me_in_prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

volumes:
  postgres_data:
